# Generated by Django 4.1.7 on 2023-05-05 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_jogo', models.CharField(max_length=50)),
                ('data_jogo', models.DateTimeField(verbose_name='data do jogo')),
            ],
        ),
        migrations.CreateModel(
            name='Treino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_treino', models.CharField(max_length=50)),
                ('data_treino', models.DateTimeField(verbose_name='data de treino')),
            ],
        ),
        migrations.CreateModel(
            name='Treinador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escalão', models.CharField(max_length=50)),
                ('num_tel', models.IntegerField(unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Opcao_treino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcao_treino', models.CharField(max_length=20)),
                ('presencas', models.IntegerField(default=0)),
                ('treino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clube.treino')),
            ],
        ),
        migrations.CreateModel(
            name='Opcao_jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcao_jogo', models.CharField(max_length=20)),
                ('presencas', models.IntegerField(default=0)),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clube.treino')),
            ],
        ),
        migrations.CreateModel(
            name='Diretor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_tel', models.IntegerField(unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Atleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disponibilidade', models.BooleanField(default=False)),
                ('escalão', models.CharField(max_length=50)),
                ('data_nascimento', models.DateField()),
                ('num_tel', models.IntegerField(unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
