# Generated by Django 4.1.7 on 2023-05-05 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clube', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atleta',
            name='sexo',
            field=models.CharField(default=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='data_jogo',
            field=models.DateTimeField(verbose_name='Data do Jogo'),
        ),
        migrations.AlterField(
            model_name='treino',
            name='data_treino',
            field=models.DateTimeField(verbose_name='Data de Treino'),
        ),
    ]
