# Generated by Django 4.1.7 on 2023-05-08 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clube', '0002_atleta_sexo_alter_jogo_data_jogo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('escalao', models.CharField(choices=[('Infantis', 'Infantis'), ('Iniciados', 'Iniciados'), ('Cadetes', 'Cadetes')], max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='treinador',
            old_name='escalão',
            new_name='equipa',
        ),
        migrations.RemoveField(
            model_name='atleta',
            name='escalão',
        ),
        migrations.AddField(
            model_name='atleta',
            name='equipa',
            field=models.CharField(default=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='data_jogo',
            field=models.DateTimeField(verbose_name='Data do Jogo: '),
        ),
        migrations.AlterField(
            model_name='treino',
            name='data_treino',
            field=models.DateTimeField(verbose_name='Data de Treino: '),
        ),
        migrations.CreateModel(
            name='Classificacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escalao', models.CharField(choices=[('Infantis', 'Infantis'), ('Iniciados', 'Iniciados'), ('Cadetes', 'Cadetes')], max_length=50)),
                ('pontos', models.IntegerField(default=0)),
                ('jogos_disputados', models.IntegerField(default=0)),
                ('jogos_ganhos', models.IntegerField(default=0)),
                ('jogos_perdidos', models.IntegerField(default=0)),
                ('equipa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clube.equipa')),
            ],
        ),
    ]
