# Generated by Django 4.1.7 on 2023-05-08 21:47

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clube', '0006_atleta_numero_alter_atleta_equipa_alter_atleta_sexo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atleta',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelManagers(
            name='atleta',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='atleta',
            name='id',
        ),
        migrations.RemoveField(
            model_name='atleta',
            name='user',
        ),
        migrations.AddField(
            model_name='atleta',
            name='user_ptr',
            field=models.OneToOneField(db_column='user_ptr_id', default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
