# Generated by Django 4.1.7 on 2023-05-08 23:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clube', '0007_alter_atleta_options_alter_atleta_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atleta',
            name='user_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Classificacoes',
        ),
        migrations.DeleteModel(
            name='Equipa',
        ),
    ]
