# Generated by Django 4.1.7 on 2023-05-08 23:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clube', '0008_alter_atleta_user_ptr_delete_classificacoes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atleta',
            options={},
        ),
        migrations.AlterModelManagers(
            name='atleta',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='atleta',
            name='disponibilidade',
        ),
        migrations.RemoveField(
            model_name='atleta',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='atleta',
            name='user_ptr',
        ),
        migrations.AddField(
            model_name='atleta',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='atleta',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='atleta',
            name='equipa',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='atleta',
            name='num_tel',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='atleta',
            name='sexo',
            field=models.CharField(max_length=10),
        ),
    ]
