# Generated by Django 4.1.7 on 2023-05-09 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clube', '0010_alter_atleta_id_alter_atleta_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Votacao_jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voto', models.BooleanField(default=False)),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='jogo',
            name='data_jogo',
        ),
        migrations.RemoveField(
            model_name='jogo',
            name='local_jogo',
        ),
        migrations.AddField(
            model_name='jogo',
            name='data',
            field=models.DateField(default=1),
        ),
        migrations.AddField(
            model_name='jogo',
            name='hora',
            field=models.TimeField(default=1),
        ),
        migrations.AddField(
            model_name='jogo',
            name='local',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.DeleteModel(
            name='Opcao_jogo',
        ),
        migrations.AddField(
            model_name='votacao_jogo',
            name='jogo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clube.jogo'),
        ),
    ]
