# Generated by Django 4.1.7 on 2023-05-09 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clube', '0011_votacao_jogo_remove_jogo_data_jogo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atleta',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
