# Generated by Django 4.1.7 on 2023-05-09 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clube', '0014_alter_atleta_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atleta',
            name='num_tel',
            field=models.IntegerField(unique=True),
        ),
    ]
