# Generated by Django 4.1.7 on 2023-05-09 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clube', '0016_alter_atleta_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atleta',
            name='equipa',
            field=models.CharField(max_length=50),
        ),
    ]
