# Generated by Django 4.1.7 on 2023-05-09 11:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clube', '0021_voto_jogo_alter_jogo_data_alter_jogo_hora_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voto_jogo',
            old_name='usuario',
            new_name='jogador',
        ),
        migrations.RenameField(
            model_name='voto_jogo',
            old_name='vai_ao_jogo',
            new_name='vai_jogar',
        ),
        migrations.RemoveField(
            model_name='voto_jogo',
            name='data',
        ),
        migrations.AddField(
            model_name='jogo',
            name='jogadores',
            field=models.ManyToManyField(through='clube.Voto_jogo', to=settings.AUTH_USER_MODEL),
        ),
    ]
