# Generated by Django 4.1.7 on 2023-05-09 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clube', '0022_rename_usuario_voto_jogo_jogador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogo',
            name='data',
            field=models.DateField(verbose_name='data'),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='local',
            field=models.CharField(max_length=200),
        ),
    ]
